# cc_binary(
#   name = 'fibonacci',
#   srcs = [
#     'fibonacci.cc',
#   ],
# )

# cc_binary(
#   name = 'threadpool',
#   srcs = [
#     'threadpool.cc',
#   ],
# )

# cc_binary(
#   name = 'blocking_queue',
#   srcs = [
#     'blocking_queue.cc',
#   ],
# )

cc_binary(
  name = 'threadsafe_queue',
  srcs = [
    'threadsafe_queue.cc',
  ],
)
